print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "D:/Emily Dang/CepheidExternProj/CepheidVR/Assets/3D Models/MayaModels/genexpert01.mb"`)
{		
	file -o "D:/Emily Dang/CepheidExternProj/CepheidVR/Assets/3D Models/MayaModels/genexpert01.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "D:/Emily Dang/CepheidExternProj/CepheidVR/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "D:/Emily Dang/CepheidExternProj/CepheidVR/Temp/CommandPipe";

$donepipeKill = `fopen "D:/Emily Dang/CepheidExternProj/CepheidVR/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
